// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using PetLink_BackEnd.Data;

#nullable disable

namespace PetLink_BackEnd.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("PetLink_BackEnd.Objects.Models.Administrador", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("email");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("nome");

                    b.Property<string>("Senha")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("senha");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.HasKey("Id");

                    b.ToTable("administrador");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Email = "miguelsilva@gmail.com",
                            Nome = "Miguel Silva",
                            Senha = "8d969eef6ecad3c29a3a629280e686cf0c3f5d5a86aff3ca12020c923adc6c92",
                            Status = 1
                        },
                        new
                        {
                            Id = 2,
                            Email = "gabrieloliveira@gmail.com",
                            Nome = "Gabriel Oliveira",
                            Senha = "8d969eef6ecad3c29a3a629280e686cf0c3f5d5a86aff3ca12020c923adc6c92",
                            Status = 1
                        },
                        new
                        {
                            Id = 3,
                            Email = "marcobrito@gmail.com",
                            Nome = "Marco Brito",
                            Senha = "8d969eef6ecad3c29a3a629280e686cf0c3f5d5a86aff3ca12020c923adc6c92",
                            Status = 2
                        });
                });

            modelBuilder.Entity("PetLink_BackEnd.Objects.Models.AgendaSlotBloqueado", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("datacriacao");

                    b.Property<DateTime>("DataHoraInicio")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("datahorainicio");

                    b.Property<string>("Motivo")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("motivo");

                    b.Property<int>("VeterinarioId")
                        .HasColumnType("integer")
                        .HasColumnName("veterinarioid");

                    b.HasKey("Id");

                    b.HasIndex("VeterinarioId", "DataHoraInicio")
                        .IsUnique();

                    b.ToTable("agendaslotbloqueado");
                });

            modelBuilder.Entity("PetLink_BackEnd.Objects.Models.AgendaVeterinario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("datacriacao");

                    b.Property<int>("DiasSemanaAtivos")
                        .HasColumnType("integer")
                        .HasColumnName("diassemanaativos");

                    b.Property<int>("DuracaoMinutos")
                        .HasColumnType("integer")
                        .HasColumnName("duracaominutos");

                    b.Property<TimeSpan>("HoraFimManha")
                        .HasColumnType("interval")
                        .HasColumnName("horafimmanha");

                    b.Property<TimeSpan>("HoraFimTarde")
                        .HasColumnType("interval")
                        .HasColumnName("horafimtarde");

                    b.Property<TimeSpan>("HoraInicioManha")
                        .HasColumnType("interval")
                        .HasColumnName("horainiciomanha");

                    b.Property<TimeSpan>("HoraInicioTarde")
                        .HasColumnType("interval")
                        .HasColumnName("horainiciotarde");

                    b.Property<int>("VeterinarioId")
                        .HasColumnType("integer")
                        .HasColumnName("veterinarioid");

                    b.HasKey("Id");

                    b.HasIndex("VeterinarioId")
                        .IsUnique();

                    b.ToTable("agendaveterinario", t =>
                        {
                            t.HasCheckConstraint("CK_agendaveterinario_dias", "diassemanaativos > 0");

                            t.HasCheckConstraint("CK_agendaveterinario_duracao", "duracaominutos = 60");

                            t.HasCheckConstraint("CK_agendaveterinario_horarios", "horainiciomanha = INTERVAL '08:00:00' AND horafimmanha = INTERVAL '11:00:00' AND horainiciotarde = INTERVAL '13:00:00' AND horafimtarde = INTERVAL '17:00:00'");
                        });
                });

            modelBuilder.Entity("PetLink_BackEnd.Objects.Models.AgendamentoConsulta", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("DataCancelamento")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("datacancelamento");

                    b.Property<DateTime?>("DataConfirmacao")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("dataconfirmacao");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("datacriacao");

                    b.Property<DateTime?>("DataHoraFim")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("datahorafim");

                    b.Property<DateTime?>("DataHoraInicio")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("datahorainicio");

                    b.Property<DateTime?>("DataRecusa")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("datarecusa");

                    b.Property<DateTime?>("DataUltimaRemarcacao")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("dataultimaremarcacao");

                    b.Property<string>("MotivoCancelamento")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("motivocancelamento");

                    b.Property<string>("MotivoRecusa")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("motivorecusa");

                    b.Property<string>("MotivoRemarcacao")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("motivoremarcacao");

                    b.Property<string>("Observacao")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("observacao");

                    b.Property<int>("OrigemSolicitacao")
                        .HasColumnType("integer")
                        .HasColumnName("origemsolicitacao");

                    b.Property<int>("PetId")
                        .HasColumnType("integer")
                        .HasColumnName("petid");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .HasColumnType("bytea")
                        .HasColumnName("rowversion");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<int>("TipoServico")
                        .HasColumnType("integer")
                        .HasColumnName("tiposervico");

                    b.Property<int?>("UltimoResponsavelRemarcacao")
                        .HasColumnType("integer")
                        .HasColumnName("ultimoresponsavelremarcacao");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("integer")
                        .HasColumnName("usuarioid");

                    b.Property<int>("VeterinarioId")
                        .HasColumnType("integer")
                        .HasColumnName("veterinarioid");

                    b.HasKey("Id");

                    b.HasIndex("PetId");

                    b.HasIndex("UsuarioId");

                    b.HasIndex("VeterinarioId", "DataHoraInicio")
                        .HasDatabaseName("IX_agendamentoconsulta_vet_inicio");

                    b.HasIndex("VeterinarioId", "DataHoraInicio", "DataHoraFim")
                        .HasDatabaseName("IX_agendamentoconsulta_vet_horario");

                    b.HasIndex("VeterinarioId", "PetId", "UsuarioId", "Status")
                        .HasDatabaseName("IX_agendamentoconsulta_pendente");

                    b.ToTable("agendamentoconsulta", t =>
                        {
                            t.HasCheckConstraint("CK_agendamentoconsulta_horario", "(datahorainicio IS NULL AND datahorafim IS NULL) OR (datahorainicio < datahorafim)");

                            t.HasCheckConstraint("CK_agendamentoconsulta_origem", "origemsolicitacao IN (1, 2)");

                            t.HasCheckConstraint("CK_agendamentoconsulta_status_datas", "(status <> 2 OR dataconfirmacao IS NOT NULL) AND (status <> 3 OR datacancelamento IS NOT NULL)");

                            t.HasCheckConstraint("CK_agendamentoconsulta_ultimo_responsavel", "ultimoresponsavelremarcacao IS NULL OR ultimoresponsavelremarcacao IN (1, 2)");
                        });
                });

            modelBuilder.Entity("PetLink_BackEnd.Objects.Models.Anuncio", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CriadorId")
                        .HasColumnType("integer")
                        .HasColumnName("criadorid");

                    b.Property<int>("CriadorTipo")
                        .HasColumnType("integer")
                        .HasColumnName("criadortipo");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("datacriacao");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("descricao");

                    b.Property<int>("OrigemEndereco")
                        .HasColumnType("integer")
                        .HasColumnName("origemendereco");

                    b.Property<int>("TipoAnuncio")
                        .HasColumnType("integer")
                        .HasColumnName("tipoanuncio");

                    b.Property<int?>("UsuarioId")
                        .HasColumnType("integer")
                        .HasColumnName("usuarioid");

                    b.HasKey("Id");

                    b.HasIndex("UsuarioId");

                    b.ToTable("anuncio");
                });

            modelBuilder.Entity("PetLink_BackEnd.Objects.Models.AnuncioPayPet", b =>
                {
                    b.Property<int>("AnuncioId")
                        .HasColumnType("integer")
                        .HasColumnName("anuncioid");

                    b.Property<int>("PetId")
                        .HasColumnType("integer")
                        .HasColumnName("petid");

                    b.Property<int>("TipoPayPet")
                        .HasColumnType("integer")
                        .HasColumnName("tipopaypet");

                    b.Property<decimal?>("Valor")
                        .HasColumnType("numeric")
                        .HasColumnName("valor");

                    b.HasKey("AnuncioId");

                    b.HasIndex("PetId");

                    b.ToTable("anuncio_paypet");
                });

            modelBuilder.Entity("PetLink_BackEnd.Objects.Models.AnuncioPeTinder", b =>
                {
                    b.Property<int>("AnuncioId")
                        .HasColumnType("integer")
                        .HasColumnName("anuncioid");

                    b.Property<int>("PetId")
                        .HasColumnType("integer")
                        .HasColumnName("petid");

                    b.HasKey("AnuncioId");

                    b.HasIndex("PetId");

                    b.ToTable("anuncio_petinder");
                });

            modelBuilder.Entity("PetLink_BackEnd.Objects.Models.AnuncioPetFinder", b =>
                {
                    b.Property<int>("AnuncioId")
                        .HasColumnType("integer")
                        .HasColumnName("anuncioid");

                    b.Property<DateTime>("DataDesaparecimento")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("datadesaparecimento");

                    b.Property<int>("PetId")
                        .HasColumnType("integer")
                        .HasColumnName("petid");

                    b.Property<string>("UltimoLocalVisto")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("ultimolocalvisto");

                    b.HasKey("AnuncioId");

                    b.HasIndex("PetId");

                    b.ToTable("anuncio_petfinder");
                });

            modelBuilder.Entity("PetLink_BackEnd.Objects.Models.EnderecoUsuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Apelido")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)")
                        .HasColumnName("apelido");

                    b.Property<bool>("Ativo")
                        .HasColumnType("boolean")
                        .HasColumnName("ativo");

                    b.Property<string>("Bairro")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("bairro");

                    b.Property<string>("Cep")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("character varying(8)")
                        .HasColumnName("cep");

                    b.Property<string>("Cidade")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("cidade");

                    b.Property<string>("Complemento")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("complemento");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("criadoem");

                    b.Property<string>("Destinatario")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("destinatario");

                    b.Property<int>("Numero")
                        .HasColumnType("integer")
                        .HasColumnName("numero");

                    b.Property<bool>("Principal")
                        .HasColumnType("boolean")
                        .HasColumnName("principal");

                    b.Property<string>("Referencia")
                        .IsRequired()
                        .HasMaxLength(140)
                        .HasColumnType("character varying(140)")
                        .HasColumnName("referencia");

                    b.Property<string>("Rua")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("rua");

                    b.Property<string>("Telefone")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("character varying(15)")
                        .HasColumnName("telefone");

                    b.Property<string>("Uf")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("character varying(2)")
                        .HasColumnName("uf");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("integer")
                        .HasColumnName("usuarioid");

                    b.HasKey("Id");

                    b.HasIndex("UsuarioId", "Principal");

                    b.ToTable("enderecousuario");
                });

            modelBuilder.Entity("PetLink_BackEnd.Objects.Models.Funcionario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("email");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("nome");

                    b.Property<decimal>("Salario")
                        .HasColumnType("numeric")
                        .HasColumnName("salario");

                    b.Property<string>("Senha")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("senha");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("funcionario");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Email = "funcionario1@petlink.com",
                            Nome = "Funcionario 1",
                            Salario = 2500.00m,
                            Senha = "8d969eef6ecad3c29a3a629280e686cf0c3f5d5a86aff3ca12020c923adc6c92"
                        },
                        new
                        {
                            Id = 2,
                            Email = "funcionario2@petlink.com",
                            Nome = "Funcionario 2",
                            Salario = 3200.00m,
                            Senha = "8d969eef6ecad3c29a3a629280e686cf0c3f5d5a86aff3ca12020c923adc6c92"
                        },
                        new
                        {
                            Id = 3,
                            Email = "funcionario3@petlink.com",
                            Nome = "Funcionario 3",
                            Salario = 4100.00m,
                            Senha = "8d969eef6ecad3c29a3a629280e686cf0c3f5d5a86aff3ca12020c923adc6c92"
                        });
                });

            modelBuilder.Entity("PetLink_BackEnd.Objects.Models.ItemPedido", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("PedidoId")
                        .HasColumnType("integer")
                        .HasColumnName("pedidoid");

                    b.Property<int>("ProdutoId")
                        .HasColumnType("integer")
                        .HasColumnName("produtoid");

                    b.Property<int>("Quantidade")
                        .HasColumnType("integer")
                        .HasColumnName("quantidade");

                    b.HasKey("Id");

                    b.HasIndex("PedidoId");

                    b.HasIndex("ProdutoId");

                    b.ToTable("itempedido");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            PedidoId = 1,
                            ProdutoId = 1,
                            Quantidade = 10
                        },
                        new
                        {
                            Id = 2,
                            PedidoId = 2,
                            ProdutoId = 2,
                            Quantidade = 5
                        });
                });

            modelBuilder.Entity("PetLink_BackEnd.Objects.Models.Pedido", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DataPedido")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("datapedido");

                    b.Property<int?>("EnderecoUsuarioId")
                        .HasColumnType("integer")
                        .HasColumnName("enderecousuarioid");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("integer")
                        .HasColumnName("usuarioid");

                    b.HasKey("Id");

                    b.HasIndex("EnderecoUsuarioId");

                    b.HasIndex("UsuarioId");

                    b.ToTable("pedido");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DataPedido = new DateTime(2025, 9, 18, 10, 20, 32, 0, DateTimeKind.Utc),
                            UsuarioId = 1
                        },
                        new
                        {
                            Id = 2,
                            DataPedido = new DateTime(2025, 9, 18, 10, 20, 32, 0, DateTimeKind.Utc),
                            UsuarioId = 2
                        });
                });

            modelBuilder.Entity("PetLink_BackEnd.Objects.Models.Pet", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Castrado")
                        .HasColumnType("boolean")
                        .HasColumnName("castrado");

                    b.Property<string>("Foto")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("foto");

                    b.Property<string>("Idade")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("idade");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("nome");

                    b.Property<float>("Peso")
                        .HasColumnType("real")
                        .HasColumnName("peso");

                    b.Property<string>("Raca")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("raca");

                    b.Property<string>("Rga")
                        .IsRequired()
                        .HasMaxLength(7)
                        .HasColumnType("character varying(7)")
                        .HasColumnName("rga");

                    b.Property<string>("Sexo")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("sexo");

                    b.Property<int>("TipoPet")
                        .HasColumnType("integer")
                        .HasColumnName("tipopet");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("integer")
                        .HasColumnName("usuarioid");

                    b.HasKey("Id");

                    b.HasIndex("UsuarioId");

                    b.ToTable("pet");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Castrado = false,
                            Foto = "https://www.prodograw.com/wp-content/uploads/2025/09/American-Pitbull-1-800x800.jpg",
                            Idade = "7 anos",
                            Nome = "Peroba",
                            Peso = 35.3f,
                            Raca = "Pit Bull",
                            Rga = "22992",
                            Sexo = "Macho",
                            TipoPet = 2,
                            UsuarioId = 1
                        },
                        new
                        {
                            Id = 2,
                            Castrado = true,
                            Foto = "https://images.tcdn.com.br/img/img_prod/1087789/noticia_619419434679a87734bc0e.png",
                            Idade = "3 anos",
                            Nome = "Felipina",
                            Peso = 5.5f,
                            Raca = "Yorkshire",
                            Rga = "22392",
                            Sexo = "Fêmea",
                            TipoPet = 2,
                            UsuarioId = 2
                        },
                        new
                        {
                            Id = 3,
                            Castrado = false,
                            Foto = "https://imgs.search.brave.com/Zf7U4EzVoIouXr_8pci0FiteQUnpCBmJF6NO38G0qdo/rs:fit:860:0:0:0/g:ce/aHR0cHM6Ly9tZWRp/YS5pc3RvY2twaG90/by5jb20vaWQvNDcy/NDY3OTUyL3B0L2Zv/dG8vYyVDMyVBM28t/cGFzdG9yLWFsZW0l/QzMlQTNvLWNhY2hv/cnJpbmhvLXRyaXN0/ZS1jJUMzJUEzby1k/ZWl0YWRvLW9saGFu/ZG8uanBnP3M9NjEy/eDYxMiZ3PTAmaz0y/MCZjPS0xV1NNYmtr/RzV1RTg5SnBPQ2NF/eU1PUllZalAxMUZP/ZzNQNWE4WXBMOXM9",
                            Idade = "8 meses",
                            Nome = "Neguin",
                            Peso = 14.9f,
                            Raca = "Pastor Alemão",
                            Rga = "22192",
                            Sexo = "Macho",
                            TipoPet = 2,
                            UsuarioId = 3
                        },
                        new
                        {
                            Id = 4,
                            Castrado = true,
                            Foto = "https://imgs.search.brave.com/OiTS8j_7NOegyditO95P5Iw58RfR0yv__Gohg9GgVe4/rs:fit:860:0:0:0/g:ce/aHR0cHM6Ly9pbWcu/ZnJlZXBpay5jb20v/Zm90b3MtZ3JhdGlz/L3JldHJhdG8tZWxl/Z2FudGUtZGUtdW0t/Z2F0by1zaWFtZXNf/MjMtMjE1MTk4MzU0/NC5qcGc_c2VtdD1h/aXNfaHlicmlkJnc9/NzQwJnE9ODA",
                            Idade = "8 anos",
                            Nome = "Garfield",
                            Peso = 5.3f,
                            Raca = "Siamês",
                            Rga = "22992",
                            Sexo = "Macho",
                            TipoPet = 1,
                            UsuarioId = 1
                        },
                        new
                        {
                            Id = 5,
                            Castrado = true,
                            Foto = "https://imgs.search.brave.com/1uVQa0yKTFnW7bqkIzG0jlsP8yOKb1kqLWWaIUFm5NM/rs:fit:860:0:0:0/g:ce/aHR0cHM6Ly9jZG4w/LmV4cGVydG9hbmlt/YWwuY29tL2VzL3Jh/emFzLzQvOC8xL2dh/dG8tcmFnZG9sbF8x/ODRfNl9vcmlnLmpw/Zw",
                            Idade = "6 meses",
                            Nome = "Tom",
                            Peso = 2.5f,
                            Raca = "Ragdoll",
                            Rga = "43432",
                            Sexo = "Macho",
                            TipoPet = 1,
                            UsuarioId = 2
                        },
                        new
                        {
                            Id = 6,
                            Castrado = true,
                            Foto = "https://imgs.search.brave.com/V0Na41tb7sTCIIeoRfAtv2KeDyLqOm3kiFDn7jKBwHo/rs:fit:860:0:0:0/g:ce/aHR0cHM6Ly9tZWRp/YS5pc3RvY2twaG90/by5jb20vaWQvMTE4/OTk3NDk1MC9waG90/by9tYWluZS1jb29u/LWNhdC1jbG9zZS11/cC1mdW5ueS1jdXRl/LWNhdC13aXRoLW1h/cmJsZS1mdXItY29s/b3ItbGFyZ2VzdC1k/b21lc3RpY2F0ZWQt/YnJlZWRzLW9mLmpw/Zz9zPTYxMng2MTIm/dz0wJms9MjAmYz16/djAzeG1iLVdFR2hE/YkNhZFRid3Z3SUxQ/N3ZwS01KTDF5eEY4/MjFhWXJJPQ",
                            Idade = "3 anos",
                            Nome = "Marie",
                            Peso = 3.2f,
                            Raca = "Coon",
                            Rga = "22192",
                            Sexo = "Fêmea",
                            TipoPet = 1,
                            UsuarioId = 3
                        });
                });

            modelBuilder.Entity("PetLink_BackEnd.Objects.Models.Produto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("descricao");

                    b.Property<string>("Foto")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("foto");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("nome");

                    b.Property<float>("Preco")
                        .HasColumnType("real")
                        .HasColumnName("preco");

                    b.Property<int>("Quantidade")
                        .HasColumnType("integer")
                        .HasColumnName("quantidade");

                    b.HasKey("Id");

                    b.ToTable("produto");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Descricao = "Ração Pedigree 500 gramas",
                            Foto = "https://imgs.search.brave.com/r1PNHaYGnd3HRBoNFQeFO3bRfx1uCwlGuwVT1mok0qo/rs:fit:860:0:0:0/g:ce/aHR0cHM6Ly9odHRw/Mi5tbHN0YXRpYy5j/b20vRF9RX05QXzJY/XzYzNjExOC1NTEE5/OTM1MDQ0MDgzOF8x/MTIwMjUtRS53ZWJw",
                            Nome = "Ração 500g",
                            Preco = 10f,
                            Quantidade = 10
                        },
                        new
                        {
                            Id = 2,
                            Descricao = "Petisco de Palito sabor bacon",
                            Foto = "https://imgs.search.brave.com/FKsGy9GxYXivL93X8J04VdbB87o_OqbnYrQk472t9P8/rs:fit:860:0:0:0/g:ce/aHR0cHM6Ly9tLm1l/ZGlhLWFtYXpvbi5j/b20vaW1hZ2VzL0kv/NDFvU0xsLU5jZkwu/anBn",
                            Nome = "Petisco de Bacon",
                            Preco = 11f,
                            Quantidade = 15
                        });
                });

            modelBuilder.Entity("PetLink_BackEnd.Objects.Models.Servico", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DataServico")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("dataServico");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)")
                        .HasColumnName("descricao");

                    b.Property<int>("PetId")
                        .HasColumnType("integer")
                        .HasColumnName("petid");

                    b.Property<int>("Tipo")
                        .HasColumnType("integer")
                        .HasColumnName("tipo");

                    b.Property<float>("Valor")
                        .HasColumnType("real")
                        .HasColumnName("valor");

                    b.HasKey("Id");

                    b.HasIndex("PetId");

                    b.ToTable("servico");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DataServico = new DateTime(2025, 10, 15, 0, 28, 32, 0, DateTimeKind.Utc),
                            Descricao = "Consulta do Joquinha",
                            PetId = 1,
                            Tipo = 1,
                            Valor = 100f
                        },
                        new
                        {
                            Id = 2,
                            DataServico = new DateTime(2025, 9, 18, 15, 20, 22, 0, DateTimeKind.Utc),
                            Descricao = "Banho da Macoca",
                            PetId = 2,
                            Tipo = 2,
                            Valor = 60f
                        },
                        new
                        {
                            Id = 3,
                            DataServico = new DateTime(2025, 6, 27, 10, 47, 2, 0, DateTimeKind.Utc),
                            Descricao = "Tosa da Penelope",
                            PetId = 3,
                            Tipo = 3,
                            Valor = 80f
                        });
                });

            modelBuilder.Entity("PetLink_BackEnd.Objects.Models.TentativaLogin", b =>
                {
                    b.Property<int>("Id").ValueGeneratedOnAdd().HasColumnType("integer").HasColumnName("id");
                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));
                    b.Property<DateTime>("AtualizadoEm").HasColumnType("timestamp with time zone").HasColumnName("atualizado_em");
                    b.Property<DateTime?>("BloqueadoAte").HasColumnType("timestamp with time zone").HasColumnName("bloqueado_ate");
                    b.Property<string>("Email").IsRequired().HasMaxLength(100).HasColumnType("character varying(100)").HasColumnName("email");
                    b.Property<int>("Falhas").HasColumnType("integer").HasColumnName("falhas");
                    b.Property<string>("Ip").IsRequired().HasMaxLength(64).HasColumnType("character varying(64)").HasColumnName("ip");
                    b.HasKey("Id");
                    b.HasIndex("Email", "Ip").IsUnique();
                    b.ToTable("tentativa_login", (string)null);
                });

            modelBuilder.Entity("PetLink_BackEnd.Objects.Models.TokenRedefinicaoSenha", b =>
                {
                    b.Property<int>("Id").ValueGeneratedOnAdd().HasColumnType("integer").HasColumnName("id");
                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));
                    b.Property<DateTime>("ExpiraEm").HasColumnType("timestamp with time zone").HasColumnName("expira_em");
                    b.Property<string>("TokenHash").IsRequired().HasMaxLength(64).HasColumnType("character varying(64)").HasColumnName("token_hash");
                    b.Property<DateTime?>("UsadoEm").HasColumnType("timestamp with time zone").HasColumnName("usado_em");
                    b.Property<int>("UsuarioId").HasColumnType("integer").HasColumnName("usuario_id");
                    b.HasKey("Id");
                    b.HasIndex("TokenHash").IsUnique();
                    b.HasIndex("UsuarioId");
                    b.ToTable("token_redefinicao_senha", (string)null);
                });

            modelBuilder.Entity("PetLink_BackEnd.Objects.Models.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Bairro")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("bairro");

                    b.Property<string>("Cep")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("character varying(8)")
                        .HasColumnName("cep");

                    b.Property<string>("Cidade")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("cidade");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("email");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("nome");

                    b.Property<int>("Numero")
                        .HasColumnType("integer")
                        .HasColumnName("numero");

                    b.Property<string>("Rua")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("rua");

                    b.Property<string>("Senha")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("senha");

                    b.Property<string>("Telefone")
                        .IsRequired()
                        .HasMaxLength(11)
                        .HasColumnType("character varying(11)")
                        .HasColumnName("telefone");

                    b.Property<string>("Uf")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("uf");

                    b.HasKey("Id");

                    b.ToTable("usuario");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Bairro = "Clone",
                            Cep = "15790000",
                            Cidade = "Rubineia",
                            Email = "gabriel@gmail.com",
                            Nome = "Gabriel",
                            Numero = 1,
                            Rua = "Rua dos Guerreiros",
                            Senha = "8d969eef6ecad3c29a3a629280e686cf0c3f5d5a86aff3ca12020c923adc6c92",
                            Telefone = "179999999",
                            Uf = "São Paulo"
                        },
                        new
                        {
                            Id = 2,
                            Bairro = "NSF",
                            Cep = "15761006",
                            Cidade = "Urânia",
                            Email = "enzo@gmail.com",
                            Nome = "Enzo",
                            Numero = 69,
                            Rua = "Travessia dos nóia",
                            Senha = "8d969eef6ecad3c29a3a629280e686cf0c3f5d5a86aff3ca12020c923adc6c92",
                            Telefone = "17997938925",
                            Uf = "São Paulo"
                        },
                        new
                        {
                            Id = 3,
                            Bairro = "Centro",
                            Cep = "15761396",
                            Cidade = "Dolcinópolis",
                            Email = "yasmin@gmail.com",
                            Nome = "Yasmin",
                            Numero = 777,
                            Rua = "Aquela rua lá",
                            Senha = "8d969eef6ecad3c29a3a629280e686cf0c3f5d5a86aff3ca12020c923adc6c92",
                            Telefone = "17997921343",
                            Uf = "São Paulo"
                        });
                });

            modelBuilder.Entity("PetLink_BackEnd.Objects.Models.Veterinario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Crmv")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("crmv");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("email");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("nome");

                    b.Property<float>("Salario")
                        .HasColumnType("real")
                        .HasColumnName("salario");

                    b.Property<string>("Senha")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("senha");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.HasKey("Id");

                    b.ToTable("veterinario");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Crmv = "4750",
                            Email = "gabriel@gmail.com",
                            Nome = "Gabriel",
                            Salario = 100000f,
                            Senha = "8d969eef6ecad3c29a3a629280e686cf0c3f5d5a86aff3ca12020c923adc6c92",
                            Status = 2
                        },
                        new
                        {
                            Id = 2,
                            Crmv = "7452",
                            Email = "enzo@gmail.com",
                            Nome = "Enzo",
                            Salario = 100000f,
                            Senha = "8d969eef6ecad3c29a3a629280e686cf0c3f5d5a86aff3ca12020c923adc6c92",
                            Status = 1
                        },
                        new
                        {
                            Id = 3,
                            Crmv = "0001",
                            Email = "yasmin@gmail.com",
                            Nome = "Yasmin",
                            Salario = 100000f,
                            Senha = "8d969eef6ecad3c29a3a629280e686cf0c3f5d5a86aff3ca12020c923adc6c92",
                            Status = 1
                        });
                });

            modelBuilder.Entity("PetLink_BackEnd.Objects.Models.AgendaSlotBloqueado", b =>
                {
                    b.HasOne("PetLink_BackEnd.Objects.Models.Veterinario", "Veterinario")
                        .WithMany()
                        .HasForeignKey("VeterinarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Veterinario");
                });

            modelBuilder.Entity("PetLink_BackEnd.Objects.Models.AgendaVeterinario", b =>
                {
                    b.HasOne("PetLink_BackEnd.Objects.Models.Veterinario", "Veterinario")
                        .WithMany()
                        .HasForeignKey("VeterinarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Veterinario");
                });

            modelBuilder.Entity("PetLink_BackEnd.Objects.Models.TokenRedefinicaoSenha", b =>
                {
                    b.HasOne("PetLink_BackEnd.Objects.Models.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("PetLink_BackEnd.Objects.Models.AgendamentoConsulta", b =>
                {
                    b.HasOne("PetLink_BackEnd.Objects.Models.Pet", "Pet")
                        .WithMany()
                        .HasForeignKey("PetId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("PetLink_BackEnd.Objects.Models.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("PetLink_BackEnd.Objects.Models.Veterinario", "Veterinario")
                        .WithMany()
                        .HasForeignKey("VeterinarioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Pet");

                    b.Navigation("Usuario");

                    b.Navigation("Veterinario");
                });

            modelBuilder.Entity("PetLink_BackEnd.Objects.Models.Anuncio", b =>
                {
                    b.HasOne("PetLink_BackEnd.Objects.Models.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("PetLink_BackEnd.Objects.Models.AnuncioPayPet", b =>
                {
                    b.HasOne("PetLink_BackEnd.Objects.Models.Anuncio", "Anuncio")
                        .WithOne()
                        .HasForeignKey("PetLink_BackEnd.Objects.Models.AnuncioPayPet", "AnuncioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PetLink_BackEnd.Objects.Models.Pet", "Pet")
                        .WithMany()
                        .HasForeignKey("PetId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Anuncio");

                    b.Navigation("Pet");
                });

            modelBuilder.Entity("PetLink_BackEnd.Objects.Models.AnuncioPeTinder", b =>
                {
                    b.HasOne("PetLink_BackEnd.Objects.Models.Anuncio", "Anuncio")
                        .WithOne()
                        .HasForeignKey("PetLink_BackEnd.Objects.Models.AnuncioPeTinder", "AnuncioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PetLink_BackEnd.Objects.Models.Pet", "Pet")
                        .WithMany()
                        .HasForeignKey("PetId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Anuncio");

                    b.Navigation("Pet");
                });

            modelBuilder.Entity("PetLink_BackEnd.Objects.Models.AnuncioPetFinder", b =>
                {
                    b.HasOne("PetLink_BackEnd.Objects.Models.Anuncio", "Anuncio")
                        .WithOne()
                        .HasForeignKey("PetLink_BackEnd.Objects.Models.AnuncioPetFinder", "AnuncioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PetLink_BackEnd.Objects.Models.Pet", "Pet")
                        .WithMany()
                        .HasForeignKey("PetId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Anuncio");

                    b.Navigation("Pet");
                });

            modelBuilder.Entity("PetLink_BackEnd.Objects.Models.EnderecoUsuario", b =>
                {
                    b.HasOne("PetLink_BackEnd.Objects.Models.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("PetLink_BackEnd.Objects.Models.ItemPedido", b =>
                {
                    b.HasOne("PetLink_BackEnd.Objects.Models.Pedido", "Pedido")
                        .WithMany()
                        .HasForeignKey("PedidoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PetLink_BackEnd.Objects.Models.Produto", "Produto")
                        .WithMany()
                        .HasForeignKey("ProdutoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Pedido");

                    b.Navigation("Produto");
                });

            modelBuilder.Entity("PetLink_BackEnd.Objects.Models.Pedido", b =>
                {
                    b.HasOne("PetLink_BackEnd.Objects.Models.EnderecoUsuario", "EnderecoUsuario")
                        .WithMany()
                        .HasForeignKey("EnderecoUsuarioId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("PetLink_BackEnd.Objects.Models.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("EnderecoUsuario");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("PetLink_BackEnd.Objects.Models.Pet", b =>
                {
                    b.HasOne("PetLink_BackEnd.Objects.Models.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("PetLink_BackEnd.Objects.Models.Servico", b =>
                {
                    b.HasOne("PetLink_BackEnd.Objects.Models.Pet", "Pet")
                        .WithMany()
                        .HasForeignKey("PetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Pet");
                });
#pragma warning restore 612, 618
        }
    }
}
