import { StyleSheet } from "react-native";

export const managementTheme = {
  colors: {
    background: "#080d16",
    backgroundMid: "#101827",
    backgroundSoft: "#12221f",
    surface: "rgba(15, 23, 42, 0.88)",
    surfaceStrong: "rgba(17, 24, 39, 0.96)",
    surfaceMuted: "rgba(30, 41, 59, 0.66)",
    surfaceMutedStrong: "rgba(31, 41, 55, 0.82)",
    border: "rgba(148, 163, 184, 0.22)",
    borderStrong: "rgba(203, 213, 225, 0.28)",
    primary: "#2563eb",
    primaryStrong: "#1d4ed8",
    primarySoft: "rgba(37, 99, 235, 0.18)",
    success: "#10b981",
    successSoft: "rgba(16, 185, 129, 0.18)",
    warning: "#f59e0b",
    warningSoft: "rgba(245, 158, 11, 0.18)",
    danger: "#ef4444",
    dangerSoft: "rgba(239, 68, 68, 0.18)",
    text: "#f8fafc",
    textStrong: "#ffffff",
    textMuted: "#cbd5e1",
    textSubtle: "#94a3b8",
    accent: "#38bdf8",
    accentWarm: "#f59e0b",
    inputText: "#0f172a",
  },
  gradients: {
    app: ["#080d16", "#101827", "#10231f"] as const,
    card: ["rgba(15,23,42,0.98)", "rgba(17,24,39,0.98)"] as const,
    hero: ["rgba(37,99,235,0.28)", "rgba(16,185,129,0.16)"] as const,
  },
  radii: {
    xs: 8,
    sm: 10,
    md: 12,
    lg: 16,
    xl: 18,
  },
  spacing: {
    pageX: 24,
    pageY: 22,
    card: 18,
  },
};

export const managementStyles = StyleSheet.create({
  screen: {
    flex: 1,
  },
  content: {
    width: "100%",
    maxWidth: 1180,
    alignSelf: "center",
    paddingHorizontal: managementTheme.spacing.pageX,
    paddingVertical: managementTheme.spacing.pageY,
    gap: 16,
  },
  topBar: {
    minHeight: 52,
    borderWidth: 1,
    borderColor: managementTheme.colors.border,
    backgroundColor: "rgba(8, 13, 22, 0.72)",
    borderRadius: managementTheme.radii.lg,
    paddingHorizontal: 14,
    paddingVertical: 10,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 12,
  },
  brandWrap: {
    flexDirection: "row",
    alignItems: "center",
    gap: 10,
    flexShrink: 1,
  },
  brandMark: {
    width: 32,
    height: 32,
    borderRadius: 9,
    backgroundColor: managementTheme.colors.primary,
    alignItems: "center",
    justifyContent: "center",
  },
  brandTitle: {
    color: managementTheme.colors.textStrong,
    fontSize: 14,
    fontWeight: "800",
  },
  brandSubtitle: {
    color: managementTheme.colors.textSubtle,
    fontSize: 11,
    marginTop: 1,
  },
  headerCard: {
    borderWidth: 1,
    borderColor: managementTheme.colors.borderStrong,
    backgroundColor: managementTheme.colors.surfaceStrong,
    borderRadius: managementTheme.radii.xl,
    padding: 20,
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "flex-start",
    gap: 16,
  },
  headerTextWrap: {
    flex: 1,
  },
  eyebrow: {
    color: managementTheme.colors.accent,
    fontSize: 12,
    fontWeight: "800",
    marginBottom: 5,
    textTransform: "uppercase",
  },
  title: {
    color: managementTheme.colors.text,
    fontSize: 30,
    fontWeight: "800",
    lineHeight: 36,
  },
  subtitle: {
    color: managementTheme.colors.textMuted,
    marginTop: 6,
    fontSize: 14,
    lineHeight: 21,
    maxWidth: 760,
  },
  panel: {
    borderWidth: 1,
    borderColor: managementTheme.colors.border,
    backgroundColor: managementTheme.colors.surface,
    borderRadius: managementTheme.radii.lg,
    padding: managementTheme.spacing.card,
    gap: 12,
  },
  toolbar: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 10,
    flexWrap: "wrap",
  },
  primaryButton: {
    flexDirection: "row",
    alignItems: "center",
    gap: 7,
    backgroundColor: managementTheme.colors.primary,
    borderRadius: managementTheme.radii.md,
    paddingVertical: 10,
    paddingHorizontal: 14,
  },
  secondaryButton: {
    flexDirection: "row",
    alignItems: "center",
    gap: 7,
    backgroundColor: "rgba(30, 41, 59, 0.72)",
    borderWidth: 1,
    borderColor: managementTheme.colors.borderStrong,
    borderRadius: managementTheme.radii.md,
    paddingVertical: 9,
    paddingHorizontal: 12,
  },
  buttonText: {
    color: "#fff",
    fontWeight: "800",
    fontSize: 13,
  },
  secondaryButtonText: {
    color: managementTheme.colors.text,
    fontWeight: "800",
    fontSize: 13,
  },
  infoText: {
    color: managementTheme.colors.textMuted,
    fontSize: 14,
    lineHeight: 20,
  },
  emptyState: {
    minHeight: 112,
    alignItems: "center",
    justifyContent: "center",
    gap: 8,
    padding: 18,
  },
  emptyTitle: {
    color: managementTheme.colors.text,
    fontSize: 15,
    fontWeight: "800",
    textAlign: "center",
  },
  emptyDescription: {
    color: managementTheme.colors.textMuted,
    fontSize: 13,
    lineHeight: 18,
    textAlign: "center",
  },
  itemCard: {
    borderWidth: 1,
    borderColor: managementTheme.colors.border,
    backgroundColor: managementTheme.colors.surfaceMutedStrong,
    borderRadius: managementTheme.radii.md,
    padding: 12,
    flexDirection: "row",
    justifyContent: "space-between",
    gap: 10,
  },
  statusPill: {
    alignSelf: "flex-start",
    borderRadius: 999,
    paddingHorizontal: 8,
    paddingVertical: 4,
    overflow: "hidden",
    color: "#ecfdf5",
    fontSize: 11,
    fontWeight: "800",
  },
  statusSuccess: {
    backgroundColor: managementTheme.colors.successSoft,
  },
  statusWarning: {
    backgroundColor: managementTheme.colors.warningSoft,
  },
  statusDanger: {
    backgroundColor: managementTheme.colors.dangerSoft,
  },
  input: {
    borderWidth: 1,
    borderColor: managementTheme.colors.border,
    borderRadius: managementTheme.radii.sm,
    paddingHorizontal: 12,
    paddingVertical: 10,
    color: managementTheme.colors.inputText,
    backgroundColor: "#f8fafc",
  },
  modalOverlay: {
    flex: 1,
    backgroundColor: "rgba(2,6,23,0.66)",
    justifyContent: "center",
    padding: 18,
  },
  modalCard: {
    width: "100%",
    maxWidth: 560,
    alignSelf: "center",
    borderRadius: managementTheme.radii.lg,
    borderWidth: 1,
    borderColor: managementTheme.colors.borderStrong,
    backgroundColor: "#111827",
    padding: 16,
    gap: 10,
  },
  modalTitle: {
    color: managementTheme.colors.text,
    fontSize: 18,
    fontWeight: "800",
    marginBottom: 2,
  },
  errorText: {
    color: "#fecaca",
    fontSize: 13,
    lineHeight: 18,
    marginTop: 2,
  },
});
